---
# 这个剧本在所有节点上运行
- name: 配置base源
  get_url: url=http://mirrors.aliyun.com/repo/Centos-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo

- name: 配置epel源
  get_url: url=http://mirrors.aliyun.com/repo/epel-7.repo dest=/etc/yum.repos.d/epel.repo

- name: 安装必备软件
  yum: name={{ item }} state=installed
  loop:
    - wget
    - lrzsz
    - tree
    - vim
    - unzip
    - ntpdate
  ignore_errors: yes

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 

- name: 同步系统时间
  shell: ntpdate time.windows.com
- name: crotab时间同步
  cron: name="ntpdate" minute="*/5" job="/usr/sbin/ntpdate time.windows.com >/dev/null 2>&1"
  ignore_errors: yes

- name: ssh_speed
  script: ssh.sh
  ignore_errors: yes

- name: limits.conf
  script: limits.sh
  ignore_errors: yes
  
  
  

